name: GDPR Fines JSON Feed

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright beautifulsoup4
          playwright install chromium

      - name: Run scraper script
        run: |
          python scrape_fines.py
          mkdir -p public
          mv gdpr_fines.json public/

      - name: Upload artifact for deployment (ONLY v4)
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact (ONLY v4)
        uses: actions/download-artifact@v4
        with:
          name: site
          path: public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
