name: GDPR Fines JSON Feed

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright beautifulsoup4
          playwright install chromium

      - name: Run scraper
        run: |
          python scrape_fines.py

      - name: Upload artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Download artifact (v4)
        uses: actions/download-artifact@v4
        with:
          name: site
          path: public/

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2
