name: GDPR Fines JSON Feed

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          pip install beautifulsoup4 playwright
          playwright install chromium

      - name: Run scraper script
        run: python scrape_fines.py

      - name: Prepare output directory
        run: |
          mkdir -p public
          if [ -f gdpr_fines.json ]; then
            mv gdpr_fines.json public/
          else
            echo "❌ gdpr_fines.json not found. Scraper might have failed." && exit 1
          fi

      - name: Upload artifact (v4)
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
